baseURL: https://blog.ypertex.com
copyright: Original content released under the [CC BY 4.0 International](http://creativecommons.org/licenses/by/4.0/) license
title: Ypertex Blog

menu:
    header:
        - name: Articles
          url: /articles/
          weight: 1
        - name: Series
          url: /series/
          weight: 2
        - name: Tags
          url: /tags/
          weight: 3
    social:
        - name: LinkedIn
          url: https://www.linkedin.com/in/michaelschmidle
          weight: 1
          pre: <i class="lab la-linkedin-in"></i>
        - name: Twitter
          url: https://twitter.com/MichaelSchmidle/
          weight: 2
          pre: <i class="lab la-twitter"></i>
        - name: GitHub
          url: https://github.com/MichaelSchmidle/
          weight: 3
          pre: <i class="lab la-github"></i>

params:
    author: Michael Schmidle
    cloudinary:
        baseURL: https://res.cloudinary.com/ypertex/image/upload/
        transformations:
            avatar: ar_1,c_thumb,dpr_auto,f_auto,g_face,q_auto,w_128/
            figureXl: ar_1.67,c_fill,dpr_auto,f_auto,g_auto,q_auto,w_1140/
            figureLg: ar_1.67,c_fill,dpr_auto,f_auto,g_auto,q_auto,w_960/
            figureMd: ar_1.67,c_fill,dpr_auto,f_auto,g_auto,q_auto,w_720/
            figureSm: ar_1.67,c_fill,dpr_auto,f_auto,g_auto,q_auto,w_767/
            figureXs: ar_1.67,c_fill,dpr_auto,f_auto,g_auto,q_auto,w_575/
            indexXl: ar_1,c_fill,dpr_auto,f_auto,g_auto,q_auto,w_350/
            indexLg: ar_1,c_fill,dpr_auto,f_auto,g_auto,q_auto,w_290/
            indexMd: ar_0.75,c_fill,dpr_auto,f_auto,q_auto,w_210/
            indexSm: ar_2,c_fill,dpr_auto,f_auto,q_auto,w_510/
            indexXs: ar_2,c_fill,dpr_auto,f_auto,q_auto,w_545/
    dateFormat: Jan 2, 2006
    description: Technology. Innovation. Leadership.

taxonomies:
    series: series
    tag: tags
